---
# KERBEROS_REALM=localhost
# KADMIN_PASSWORD=password
# KCLIENT_MAX_WAIT_TIME=30

version: "3.6"
services:
  kdc-kadmin:
    build:
      context: ./kdc-kadmin
    environment:
      - REALM=${KERBEROS_REALM:-localhost}
      - SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
      - KADMIN_PRINCIPAL=kadmin/admin
      - KADMIN_PASSWORD=${KADMIN_PASSWORD:-password}
    volumes:
      - /dev/urandom:/dev/random
    networks:
      cluster:
        aliases:
          - kdc-kadmin.${KERBEROS_REALM:-localhost}
  kerberos-client:
    build:
      context: ./kerberos-client
    environment:
      - REALM=${KERBEROS_REALM:-localhost}
      - SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
      - KADMIN_PRINCIPAL=kadmin/admin
      - KADMIN_PASSWORD=${KADMIN_PASSWORD:-password}
      - KCLIENT_MAX_WAIT_TIME=${KCLIENT_MAX_WAIT_TIME:-30}
    depends_on:
      - kdc-kadmin
    networks:
      cluster:
        aliases:
          - kerberos-client.${KERBEROS_REALM:-localhost}

networks:
  cluster:
    name: ${DOCKER_NETWORK_NAME:-local-cluster-kafka}
    external: true
